services:
  rekrutacjatergui:
    build: ../src/RekrutacjaTerg.UI/
    ports:
      - "8080:80"
    networks:
      - frontend
  rekrutacjatergapi:
    build: ../src/RekrutacjaTerg.API/
    ports:
      - "7084:80"
      - "7085:443"
    networks:
      - frontend
  
networks:
  frontend: